-- Extra catalog rows: trading bots, copy traders, investment products.
-- Requires migration 0011_trading_bots_cron_limits (cron sizing columns on trading_bots).
-- Safe to re-run: INSERT IGNORE. IDs avoid colliding with backend/src/db/seed.sql (bot-momentum, trader-1, inv-yield).

INSERT IGNORE INTO `trading_bots` (
  `id`,
  `name`,
  `strapline`,
  `description`,
  `strategy`,
  `price_usd`,
  `monthly_target`,
  `win_rate`,
  `max_drawdown`,
  `markets`,
  `cadence`,
  `guardrails`,
  `subscription_days`,
  `max_trades_per_day`,
  `trade_size_pct_of_fiat_balance`,
  `min_trade_size_usd`,
  `max_trade_size_usd`
) VALUES
  (
    'bot-mean-revert',
    'Mean Reversion Lab',
    'Fade stretched moves',
    'Looks for short-term overextension and scales in with tight risk bands.',
    'Mean reversion',
    39.00,
    '5–9%',
    54,
    15,
    '["SOL","ETH","AVAX"]',
    '1h',
    '["max_daily_loss_2pct","pause_on_vol_spike"]',
    30,
    4,
    0.030000,
    15.00,
    350.00
  ),
  (
    'bot-breakout',
    'Breakout Patrol',
    'Volatility expansion plays',
    'Waits for range breaks on liquid majors with trailing logic.',
    'Breakout',
    59.00,
    '8–14%',
    60,
    18,
    '["BTC","BNB","ETH"]',
    '4h',
    '["max_position_3pct_equity"]',
    30,
    3,
    0.040000,
    25.00,
    800.00
  ),
  (
    'bot-grid',
    'Grid Accumulator',
    'Range-friendly stacking',
    'Places layered entries in sideways conditions; reduces size in trends.',
    'Grid',
    35.00,
    '3–6%',
    52,
    10,
    '["ETH","LINK","MATIC"]',
    '30m',
    '["max_daily_loss_1p5pct"]',
    30,
    8,
    0.020000,
    8.00,
    220.00
  ),
  (
    'bot-scalp',
    'Scalp Pulse',
    'Short cadence signals',
    'Higher-frequency signals on top pairs; respects strict daily trade caps.',
    'Scalping',
    29.00,
    '4–7%',
    55,
    11,
    '["BTC","ETH","SOL"]',
    '15m',
    '["max_daily_loss_1pct","cooldown_after_loss"]',
    14,
    12,
    0.015000,
    5.00,
    150.00
  ),
  (
    'bot-trend-rider',
    'Trend Rider Plus',
    'Multi-timeframe trend filter',
    'Aligns entries with higher-timeframe bias; smaller size in chop.',
    'Momentum',
    55.00,
    '7–11%',
    57,
    16,
    '["BTC","ETH","DOT"]',
    '2h',
    '["max_daily_loss_2pct"]',
    30,
    5,
    0.035000,
    20.00,
    600.00
  );

INSERT IGNORE INTO `copy_traders` (
  `id`,
  `name`,
  `handle`,
  `specialty`,
  `followers`,
  `win_rate`,
  `max_drawdown`,
  `min_allocation`,
  `fee_pct`,
  `monthly_return`,
  `bio`,
  `focus_pairs`,
  `capacity`
) VALUES
  (
    'trader-2',
    'Sam Chen',
    '@schen_vol',
    'Volatility & majors',
    890,
    58,
    16,
    750,
    12,
    '3–8%',
    'Sizes down when funding is extreme; prefers BTC and ETH perps.',
    '["BTC-USDT","ETH-USDT"]',
    'Open'
  ),
  (
    'trader-3',
    'Jordan Lee',
    '@jlee_alt',
    'Large-cap alts',
    640,
    55,
    19,
    400,
    18,
    '2–7%',
    'Rotates among liquid alts; avoids illiquid listings.',
    '["SOL-USDT","AVAX-USDT","LINK-USDT"]',
    'Limited'
  ),
  (
    'trader-4',
    'Morgan Blake',
    '@mblake_swing',
    'Multi-day swings',
    1520,
    62,
    13,
    1200,
    14,
    '5–10%',
    'Holds through noise with staged exits on BTC and ETH.',
    '["BTC-USDT","ETH-USDT"]',
    'Open'
  ),
  (
    'trader-5',
    'Riley Santos',
    '@rs_defi',
    'ETH ecosystem',
    410,
    53,
    21,
    300,
    20,
    '1–6%',
    'Focus on ETH-beta names and majors only.',
    '["ETH-USDT","MATIC-USDT"]',
    'Open'
  ),
  (
    'trader-6',
    'Casey Nguyen',
    '@cnguyen_scalp',
    'Intraday liquidity',
    980,
    56,
    17,
    600,
    16,
    '4–9%',
    'Short holding periods on tight spreads.',
    '["BTC-USDT","ETH-USDT","SOL-USDT"]',
    'Limited'
  );

INSERT IGNORE INTO `investment_products` (
  `id`,
  `name`,
  `subtitle`,
  `category`,
  `vehicle`,
  `apy`,
  `term_days`,
  `min_amount`,
  `liquidity`,
  `distribution`,
  `funded_pct`,
  `risk`,
  `focus`,
  `objective`,
  `suitable_for`,
  `description`
) VALUES
  (
    'inv-term-180',
    'Core Income Bridge',
    'Six-month lock',
    'Short Term',
    'Note',
    6.7500,
    180,
    2500,
    'At maturity',
    'Quarterly',
    68,
    'Moderate',
    '["USD","USDC"]',
    'Steady yield with defined term',
    'Investors comfortable locking funds for half a year',
    'Illustrative structured note-style product shown in the dashboard catalog.'
  ),
  (
    'inv-growth-multi',
    'Growth Multi-Asset',
    'Balanced risk sleeve',
    'Long Term',
    'Fund',
    8.2500,
    365,
    5000,
    'Monthly',
    'Monthly',
    55,
    'High',
    '["BTC","ETH","SOL"]',
    'Long-term growth with crypto exposure',
    'Higher risk tolerance and longer horizon',
    'Demonstration product mixing majors for UI and reporting flows.'
  ),
  (
    'inv-cash-reserve',
    'Cash Reserve Plus',
    'Rolling 30-day',
    'Short Term',
    'Money market style',
    4.1000,
    30,
    500,
    'Weekly',
    'Weekly',
    81,
    'Low',
    '["USD"]',
    'Preserve principal with modest yield',
    'Conservative or short-term cash holders',
    'Short liquidity profile suitable for onboarding demos.'
  ),
  (
    'inv-retire-glide',
    'Glidepath Retirement',
    'Multi-year glide',
    'Retirement',
    'Target-date sleeve',
    7.0000,
    1095,
    10000,
    'Quarterly',
    'Quarterly',
    48,
    'Moderate',
    '["USD","BTC","ETH"]',
    'Gradual de-risking over the term',
    'Long-horizon retirement planning narratives',
    'Long-dated illustrative vehicle for retirement category in the app.'
  ),
  (
    'inv-yield-flex',
    'Flexible Yield Basket',
    'Optional top-ups',
    'Long Term',
    'Basket',
    5.9000,
    270,
    1500,
    'Monthly',
    'Monthly',
    74,
    'Moderate',
    '["USDC","ETH"]',
    'Income with some growth tilt',
    'Balanced investors seeking periodic distributions',
    'Basket-style label for catalog variety and filters in the UI.'
  );
