/** Central API path segments — align with backend Hono routes */
export const endpoints = {
  user: {
    getOtherBalance: '/user/getOtherBalance',
    wonLoss: '/user/wonLoss',
    getActivityLog: '/user/getActivityLog',
    getOpenTrades: '/user/getOpenTrades',
    getClosedTrades: '/user/getClosedTrades',
    getTradePositions: '/user/getTradePositions',
    closeTrade: '/user/closeTrade',
    login: '/user/login',
    getFiat: '/user/getFiat',
    getVerificationStatus: '/user/getVerificationStatus',
    updateUserStatus: '/user/updateUserStatus',
    addBios: '/user/addBios',
    getAllFiats: '/user/getAllFiats',
    updateCurrency: '/user/updateCurrency',
    addAdminWallet: '/user/addAdminWallet',
    welcomeOnboarding: '/user/welcomeOnboarding',
    ensureWebSession: '/user/ensureWebSession',
    me: '/user/me',
  },
  auth: {
    createToken: '/auth/createToken',
    sendOTP: '/auth/sendOTP',
    verifyOTP: '/auth/verifyOTP',
    register: '/auth/register',
    passwordReset: '/auth/passwordReset',
    verifyToken: '/auth/verifyToken',
    verifyEmailAndStartSession: '/auth/verifyEmailAndStartSession',
    verificationPoll: '/auth/verificationPoll',
    sendVerificationEmail: '/auth/sendVerificationEmail',
    sendLoginOtpEmail: '/auth/sendLoginOtpEmail',
    loginNotification: '/auth/loginNotification',
  },
  affiliate: {
    summary: '/affiliate/summary',
    referrals: '/affiliate/referrals',
  },
  wallet: {
    assets: '/wallet/assets',
    transactions: '/wallet/transactions',
    convert: '/wallet/convert',
  },
  admin: {
    faqCategories: '/admin/getFAQcat',
    faqByCategory: (catId: number) => `/admin/getFAQ?catId=${catId}`,
    stats: '/admin/stats',
    users: '/admin/users',
    usersFiatUsdBalances: '/admin/users/fiat-usd-balances',
    user: (id: string) => `/admin/users/${encodeURIComponent(id)}`,
    userBios: (id: string) => `/admin/users/${encodeURIComponent(id)}/bios`,
    userVerification: (id: string) => `/admin/users/${encodeURIComponent(id)}/verification`,
    userRole: (id: string) => `/admin/users/${encodeURIComponent(id)}/role`,
    userFundFiat: (id: string) => `/admin/users/${encodeURIComponent(id)}/fund-fiat`,
    userFundAsset: (id: string) => `/admin/users/${encodeURIComponent(id)}/fund-asset`,
    userWalletAdjust: (id: string) => `/admin/users/${encodeURIComponent(id)}/wallet-adjust`,
    trades: '/admin/trades',
    createTrade: '/admin/trades/create',
    bots: '/admin/bots',
    bot: (id: string) => `/admin/bots/${encodeURIComponent(id)}`,
    copyTraders: '/admin/copy-traders',
    copyTrader: (id: string) => `/admin/copy-traders/${encodeURIComponent(id)}`,
    investments: '/admin/investments',
    investment: (id: string) => `/admin/investments/${encodeURIComponent(id)}`,
  },
  platform: {
    tradingBots: '/platform/trading-bots',
    copyTraders: '/platform/copy-traders',
    investmentProducts: '/platform/investment-products',
    copyAllocations: '/platform/copy-allocations',
    botSubscriptions: '/platform/bot-subscriptions',
    botSubscribe: '/platform/bot-subscriptions',
    botUnsubscribe: (botId: string) =>
      `/platform/bot-subscriptions/${encodeURIComponent(botId)}`,
    coins: '/platform/coins',
    addCoin: '/platform/coins',
    followingTraders: '/platform/following-traders',
    followTraderAllocate: '/platform/following-traders',
    investmentPositions: '/platform/investment-positions',
    investPosition: '/platform/investment-positions',
  },
  crypto: {
    price: '/crypto/price',
    history: '/crypto/history',
    news: '/crypto/news',
    coinDetail: '/crypto/coin-detail',
  },
  settings: {
    toggles: '/settings/toggles',
    updateToggle: (toggleId: string) => `/settings/toggles/${encodeURIComponent(toggleId)}`,
    activityLogs: '/settings/activity-logs',
  },
  verification: {
    overview: '/verification/overview',
    steps: '/verification/steps',
    documents: '/verification/documents',
    benefits: '/verification/benefits',
    documentUpload: (documentId: string) =>
      `/verification/documents/${encodeURIComponent(documentId)}/upload`,
    documentDownload: (documentId: string) =>
      `/verification/documents/${encodeURIComponent(documentId)}/download`,
  },
  live: {
    orderBookWs: (pair: string) => `/live/ws/${encodeURIComponent(pair)}`,
    placeOrder: '/live/orders',
    cancelOrder: '/live/orders/cancel',
  },
} as const
